version: '3'
services:
  tomcat-server:
    container_name: tomcat-server
    build: .
    volumes:
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
      - "8000:8000"
    command: >
      bash -c "mvn clean install 
      && mvn tomcat7:run"
    links:
      - db

  db:
    container_name: db
    build: ./DockerDb
    ports:
      - "5434:5432"
  adminer:
        container_name: dbAdmin
        image: adminer
        restart: always
        ports:
          - 8082:8080
        links:
          - db
